### ISSUE TITLE
There are no shortcuts

### ISSUE THREAD

**Issue by rustygloves** [adrianmoisey/bash-shortcuts#1]
This repo is called `bash-shortcuts` but there are no shortcuts

**Comment by adrianmoisey** [comment]
That’s the shortcut! ☺️

**Comment by adrianmoisey** [comment]
Hey @rustygloves, I got some shortcuts added.
It's not a lot, but mostly for me to glance at and ensuring I get memorised. More to come later.

If you have any you want to add, please feel free to make a PR.
